const seedTalent = [
  {name:'Amara Osei', role:'Brand designer & visual storyteller', category:'Design', price:'$2,400', location:'London, UK', rating:'5.0', reviews:'24', image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85', service:'Brand identity sprint with Amara Osei'},
  {name:'Jon Bell', role:'Product designer for growing teams', category:'Design', price:'$1,850', location:'Brooklyn, NY', rating:'4.9', reviews:'41', image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=700&q=85', service:'Product design sprint with Jon Bell'},
  {name:'Mina Park', role:'Web developer & creative technologist', category:'Development', price:'$3,200', location:'Seoul, KR', rating:'5.0', reviews:'18', image:'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=700&q=85', service:'Creative development with Mina Park'},
  {name:'Theo Laurent', role:'Writer, editor & brand voice', category:'Writing', price:'$950', location:'Paris, FR', rating:'4.8', reviews:'37', image:'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=700&q=85', service:'Brand voice workshop with Theo Laurent'}
];
const generatedNames = ['Avery','Samira','Noah','Elena','Ravi','Clara','Mateo','Nia','Luca','Priya'];
const generatedSurnames = ['Morgan','Okafor','Chen','Rivera','Shaw','Bennett','Singh','Davis','Khan','Moreau'];
const generatedLocations = ['Austin, US','Toronto, CA','Berlin, DE','Melbourne, AU','Lisbon, PT','Nairobi, KE','Amsterdam, NL','Osaka, JP'];
const generatedCategories = [
  {category:'Design', role:'Independent visual designer'},
  {category:'Development', role:'Product developer for modern teams'},
  {category:'Writing', role:'Writer and thoughtful editor'},
  {category:'Marketing', role:'Marketing strategist for growing brands'}
];
const categoryImages = {
  Design: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85',
  Development: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=700&q=85',
  Writing: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=700&q=85',
  Marketing: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=700&q=85'
};
const generatedTalent = Array.from({length:100}, (_, index) => {
  const name = `${generatedNames[index % generatedNames.length]} ${generatedSurnames[Math.floor(index / generatedNames.length)]}`;
  const specialty = generatedCategories[index % generatedCategories.length];
  const price = 700 + ((index * 137) % 2800);
  return {name, role:specialty.role, category:specialty.category, price:`$${price.toLocaleString()}`, location:generatedLocations[index % generatedLocations.length], rating:(4.6 + ((index % 5) / 10)).toFixed(1), reviews:String(8 + (index % 43)), image:categoryImages[specialty.category], service:`${specialty.category} service with ${name}`};
});
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const catalogTalent = [...seedTalent.map(item => ({...item, image:categoryImages[item.category]})), ...generatedTalent];
const storedTalent = read('skillconnect-services', []);
const storedByName = new Map(storedTalent.filter(item => item.owner).map(item => [item.name, item]));
let talent = [...catalogTalent.map(item => storedByName.get(item.name) || item), ...storedTalent.filter(item => item.owner && !catalogTalent.some(seed => seed.name === item.name))];
let allTalentOrder = [...talent].sort(() => Math.random() - 0.5);
let bookings = read('skillconnect-bookings', []);
let users = read('skillconnect-users', []);
let currentUser = read('skillconnect-user', null);
if (currentUser && !users.some(user => user.email === currentUser.email)) { currentUser = null; localStorage.removeItem('skillconnect-user'); }
let activeCategory = 'All'; let authMode = 'login'; let visibleLimit = 4;
const grid = document.querySelector('#talent-grid'); const searchInput = document.querySelector('#hero-search'); const sortSelect = document.querySelector('#sort-select'); const toast = document.querySelector('#toast');
const modal = id => document.querySelector(id);
function showToast(message) { toast.textContent=message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>toast.classList.remove('show'),3400); }
function renderTalent() { const term=(searchInput?.value||'').trim().toLowerCase(); const source=activeCategory==='All'?allTalentOrder:talent; let matches=source.filter(person=>(activeCategory==='All'||person.category===activeCategory)&&(!term||`${person.name} ${person.role} ${person.category} ${person.location}`.toLowerCase().includes(term))); if(sortSelect?.value==='rating') matches=[...matches].sort((a,b)=>Number(b.rating)-Number(a.rating)); if(sortSelect?.value==='price') matches=[...matches].sort((a,b)=>Number(a.price.replace(/\D/g,''))-Number(b.price.replace(/\D/g,''))); const visible=matches.slice(0,visibleLimit); const saved=read('skillconnect-saved',[]); grid.innerHTML=visible.length?visible.map(person=>{const initials=person.name.split(' ').map(part=>part[0]).join('').slice(0,2);return `<article class="talent-card"><div class="talent-image"><img src="${person.image}" alt="${person.name}, ${person.role}"><div class="profile-overlay"><span class="profile-category">${person.category}</span><strong class="profile-initials">${initials}</strong><div class="profile-image-footer"><span>${person.name}</span><span>from ${person.price}</span></div></div><button class="save-button ${saved.includes(person.name)?'saved':''}" data-save="${person.name}" aria-label="${saved.includes(person.name)?'Remove':'Add'} ${person.name} ${saved.includes(person.name)?'from':'to'} shortlist">${saved.includes(person.name)?'♥':'♡'}</button></div><div class="talent-info"><p class="talent-role">${person.role}</p><div class="talent-meta"><span>${person.location}</span><span class="rating">★ ${person.rating} <span>(${person.reviews})</span></span></div><button class="book-button" data-book="${person.service}">Book now <span>↗</span></button></div></article>`}).join(''):'<div class="empty-state"><h3>No one by that brief yet.</h3><p>Try another category or search term.</p></div>'; document.querySelector('#result-count').textContent=`Showing ${visible.length} of ${matches.length} talents`; const viewAllButton=document.querySelector('[data-action="load-more"]'); if(viewAllButton){viewAllButton.innerHTML=visible.length<matches.length?`View all ${matches.length} <span>↗</span>`:'Showing all <span>✓</span>';viewAllButton.disabled=visible.length>=matches.length;} grid.querySelectorAll('[data-book]').forEach(button=>button.addEventListener('click',()=>openBooking(button.dataset.book))); grid.querySelectorAll('[data-save]').forEach(button=>button.addEventListener('click',()=>{if(!currentUser){showToast('Log in to save talent to your shortlist.');openAuth('login');return;}let list=read('skillconnect-saved',[]);list=list.includes(button.dataset.save)?list.filter(name=>name!==button.dataset.save):[...list,button.dataset.save];write('skillconnect-saved',list);renderTalent();if(!modal('#dashboard-modal').classList.contains('open'))showToast(list.includes(button.dataset.save)?'Saved to your shortlist.':'Removed from your shortlist.');renderShortlist();})); }
function openDialog(id) { const el=modal(id); el.classList.add('open'); el.setAttribute('aria-hidden','false'); }
function closeDialog(id) { const el=modal(id); el.classList.remove('open'); el.setAttribute('aria-hidden','true'); }
function openBooking(service) { document.querySelector('#modal-service').textContent=service; document.querySelector('#booking-email').value=currentUser?.email||''; openDialog('#booking-modal'); document.querySelector('#booking-email').focus(); }
function openAuth(mode='login') { authMode=mode; document.querySelector('#auth-error').textContent=''; document.querySelector('#auth-title').innerHTML=mode==='login'?'Welcome<br><em>back.</em>':'Make room for<br><em>good work.</em>'; document.querySelector('#auth-kicker').textContent=mode==='login'?'A calm place for good work':'Join the independent economy'; document.querySelector('#auth-name').required=mode==='signup'; document.querySelector('#auth-name').classList.toggle('hidden',mode==='login'); document.querySelector('#auth-submit').innerHTML=mode==='login'?'Log in <span>↗</span>':'Create account <span>↗</span>'; document.querySelector('#switch-auth').textContent=mode==='login'?'Need an account? Create one':'Already have an account? Log in'; openDialog('#auth-modal'); if(mode==='login') document.querySelector('#auth-email').focus(); else document.querySelector('#auth-name').focus(); }
async function hashPassword(password) { const data = new TextEncoder().encode(password); const hash = await crypto.subtle.digest('SHA-256', data); return Array.from(new Uint8Array(hash)).map(byte => byte.toString(16).padStart(2, '0')).join(''); }
function updateAccountUI() { for (const id of ['#login-button','#mobile-login-button','#signup-button','#mobile-signup-button']) document.querySelector(id).classList.toggle('hidden',!!currentUser); for (const id of ['#account-button','#mobile-account-button']) document.querySelector(id).classList.toggle('hidden',!currentUser); }
function renderDashboard() { const name=currentUser?.name||'Local member'; document.querySelector('#dashboard-user').textContent=`${name} · demo account`; document.querySelector('#booking-count').textContent=bookings.length; document.querySelector('#shortlist-count').textContent=read('skillconnect-saved',[]).length; document.querySelector('#service-count').textContent=talent.filter(item=>item.owner).length; const bookingPanel=modal('#bookings-panel'); bookingPanel.innerHTML=bookings.length?bookings.map(item=>`<div class="dashboard-item"><div><strong>${item.service}</strong><small>${item.email} · ${item.created}</small></div><span class="status-pill">REQUESTED</span></div>`).join(''):'<div class="empty-dashboard">No bookings yet. Browse the catalog and request a service to see it here.</div>'; renderShortlist(); renderServices(); }
function renderShortlist() { const names=read('skillconnect-saved',[]); const items=names.map(name=>talent.find(person=>person.name===name)).filter(Boolean); document.querySelector('#shortlist-count').textContent=items.length; modal('#shortlist-panel').innerHTML=items.length?items.map(person=>`<div class="dashboard-item"><div><strong>${person.name}</strong><small>${person.category} · ${person.role} · from ${person.price}</small></div><div class="shortlist-actions"><button class="outline-button" data-shortlist-book="${person.service}">Book now</button><button class="remove-shortlist" data-unsave="${person.name}" aria-label="Remove ${person.name} from shortlist">×</button></div></div>`).join(''):'<div class="empty-dashboard">Your shortlist is empty. Save talent from the catalog to keep them here.</div>'; modal('#shortlist-panel').querySelectorAll('[data-shortlist-book]').forEach(button=>button.addEventListener('click',()=>openBooking(button.dataset.shortlistBook))); modal('#shortlist-panel').querySelectorAll('[data-unsave]').forEach(button=>button.addEventListener('click',()=>{write('skillconnect-saved',read('skillconnect-saved',[]).filter(name=>name!==button.dataset.unsave));renderDashboard();renderTalent();showToast('Removed from your shortlist.');})); }
function renderServices() { const list=modal('#service-list'); const owned=talent.filter(item=>item.owner); list.innerHTML=owned.length?owned.map(item=>`<div class="service-row"><div><strong>${item.name}</strong><small>${item.category} · from $${Number(item.price.replace(/\D/g,'' )).toLocaleString()}</small></div><div class="service-actions"><button data-edit-service="${item.id}">Edit</button><button data-delete-service="${item.id}">Delete</button></div></div>`).join(''):'<div class="empty-dashboard">Add your first service above. It will persist in this browser.</div>'; list.querySelectorAll('[data-edit-service]').forEach(button=>button.addEventListener('click',()=>editService(button.dataset.editService))); list.querySelectorAll('[data-delete-service]').forEach(button=>button.addEventListener('click',()=>deleteService(button.dataset.deleteService))); }
function editService(id) { const service=talent.find(item=>item.id===id); document.querySelector('#service-id').value=id; document.querySelector('#service-title').value=service.name; document.querySelector('#service-category').value=service.category; document.querySelector('#service-price').value=Number(service.price.replace(/\D/g,'')); document.querySelector('#service-submit').innerHTML='Save changes <span>↗</span>'; document.querySelector('#cancel-service').classList.remove('hidden'); }
function deleteService(id) { if(!confirm('Delete this service from your demo studio?')) return; talent=talent.filter(item=>item.id!==id); allTalentOrder=allTalentOrder.filter(item=>item.id!==id); write('skillconnect-services',talent); renderTalent(); renderDashboard(); showToast('Service deleted.'); }
document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{activeCategory=button.dataset.category;visibleLimit=4;document.querySelectorAll('[data-category]').forEach(item=>item.classList.toggle('active',item===button));renderTalent();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});}));
document.querySelectorAll('[data-search]').forEach(button=>button.addEventListener('click',()=>{searchInput.value=button.dataset.search;visibleLimit=4;renderTalent();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});})); searchInput?.addEventListener('input',()=>{visibleLimit=4;renderTalent();}); sortSelect?.addEventListener('change',()=>{visibleLimit=4;renderTalent();});
document.querySelector('[data-action="search"]')?.addEventListener('click',()=>{renderTalent();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});}); document.querySelector('[data-action="focus-search"]')?.addEventListener('click',()=>{searchInput?.focus();document.querySelector('#search-panel').scrollIntoView({behavior:'smooth',block:'center'});});
const menuButton=document.querySelector('.mobile-menu');
function closeMobileMenu() { document.querySelector('.topbar').classList.remove('mobile-open'); menuButton.setAttribute('aria-expanded','false'); }
menuButton.addEventListener('click',()=>{const open=document.querySelector('.topbar').classList.toggle('mobile-open');menuButton.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',closeMobileMenu));
document.querySelector('.filter-button')?.addEventListener('click',()=>showToast('Use categories, search, and sort to refine the catalog.'));
document.querySelectorAll('[data-action="login"]').forEach(button=>button.addEventListener('click',()=>{closeMobileMenu();openAuth('login');}));
document.querySelectorAll('[data-action="signup"]').forEach(button=>button.addEventListener('click',()=>{closeMobileMenu();openAuth('signup');}));
document.querySelector('#create-profile-button').addEventListener('click',()=>{if(!currentUser){openAuth('signup');return;}renderDashboard();document.querySelector('[data-tab="services"]').click();openDialog('#dashboard-modal');});
document.querySelectorAll('[data-action="dashboard"]').forEach(button=>button.addEventListener('click',()=>{closeMobileMenu();renderDashboard();openDialog('#dashboard-modal');}));
document.querySelector('[data-action="load-more"]')?.addEventListener('click',()=>{visibleLimit=Number.MAX_SAFE_INTEGER;renderTalent();showToast('All available talents are now shown.');});
document.querySelector('[data-action="close-modal"]')?.addEventListener('click',()=>closeDialog('#booking-modal')); document.querySelector('[data-action="close-auth"]')?.addEventListener('click',()=>closeDialog('#auth-modal')); document.querySelector('[data-action="close-dashboard"]')?.addEventListener('click',()=>closeDialog('#dashboard-modal')); document.querySelector('#switch-auth')?.addEventListener('click',()=>openAuth(authMode==='login'?'signup':'login'));
modal('#booking-modal')?.addEventListener('click',e=>{if(e.target===modal('#booking-modal'))closeDialog('#booking-modal')}); modal('#auth-modal')?.addEventListener('click',e=>{if(e.target===modal('#auth-modal'))closeDialog('#auth-modal')}); modal('#dashboard-modal')?.addEventListener('click',e=>{if(e.target===modal('#dashboard-modal'))closeDialog('#dashboard-modal')});
document.querySelector('#booking-form')?.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target);bookings.unshift({service:document.querySelector('#modal-service').textContent,email:form.get('email'),created:new Date().toLocaleDateString()});write('skillconnect-bookings',bookings);closeDialog('#booking-modal');event.target.reset();showToast('Request saved to your demo workspace.');});
document.querySelector('#auth-form')?.addEventListener('submit',async event=>{event.preventDefault();const email=document.querySelector('#auth-email').value.trim().toLowerCase();const password=document.querySelector('#auth-password').value;const error=document.querySelector('#auth-error');error.textContent='';const passwordHash=await hashPassword(password);if(authMode==='signup'){if(users.some(user=>user.email===email)){error.textContent='An account with this email already exists. Log in instead.';return;}const name=document.querySelector('#auth-name').value.trim();const account={id:crypto.randomUUID(),name,email,passwordHash,role:'CLIENT'};users.push(account);write('skillconnect-users',users);currentUser={id:account.id,name,email,role:account.role};write('skillconnect-user',currentUser);updateAccountUI();closeDialog('#auth-modal');showToast('Your demo account is ready, '+name+'.');event.target.reset();return;}const account=users.find(user=>user.email===email);if(!account||account.passwordHash!==passwordHash){error.textContent='Email or password is incorrect. Create an account first if you are new here.';return;}currentUser={id:account.id,name:account.name,email:account.email,role:account.role};write('skillconnect-user',currentUser);updateAccountUI();closeDialog('#auth-modal');showToast('Welcome back, '+account.name+'.');event.target.reset();});
document.querySelector('#logout-button')?.addEventListener('click',()=>{currentUser=null;localStorage.removeItem('skillconnect-user');updateAccountUI();closeDialog('#dashboard-modal');showToast('You are logged out of this browser.');});
document.querySelectorAll('.dashboard-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.dashboard-tab').forEach(item=>item.classList.toggle('active',item===tab));document.querySelector('#bookings-panel').classList.toggle('hidden',tab.dataset.tab!=='bookings');document.querySelector('#shortlist-panel').classList.toggle('hidden',tab.dataset.tab!=='shortlist');document.querySelector('#services-panel').classList.toggle('hidden',tab.dataset.tab!=='services');}));
document.querySelector('#service-form')?.addEventListener('submit',event=>{event.preventDefault();const id=document.querySelector('#service-id').value;const title=document.querySelector('#service-title').value;const category=document.querySelector('#service-category').value;const price=Number(document.querySelector('#service-price').value);if(id){const item=talent.find(service=>service.id===id);Object.assign(item,{name:title,category,price:`$${price.toLocaleString()}`,image:categoryImages[category]});showToast('Service updated.');}else{talent.push({id:crypto.randomUUID(),owner:true,name:title,role:'Independent talent on SkillConnect',category,price:`$${price.toLocaleString()}`,location:'Your location',rating:'New',reviews:'0',image:categoryImages[category],service:title});showToast('Service created.');}allTalentOrder=[...talent].sort(() => Math.random() - 0.5);write('skillconnect-services',talent);event.target.reset();document.querySelector('#service-id').value='';document.querySelector('#service-submit').innerHTML='Add service <span>↗</span>';document.querySelector('#cancel-service').classList.add('hidden');renderTalent();renderDashboard();});
document.querySelector('#cancel-service')?.addEventListener('click',()=>{document.querySelector('#service-form').reset();document.querySelector('#service-id').value='';document.querySelector('#service-submit').innerHTML='Add service <span>↗</span>';document.querySelector('#cancel-service').classList.add('hidden');});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){['#booking-modal','#auth-modal','#dashboard-modal'].forEach(id=>closeDialog(id));}}); updateAccountUI(); renderTalent();
